name: deploy to lambda
on: [push]
jobs:

  deploy:
    name: deploy to s3
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp 2021 \
            --recursive \
            --region ap-northeast-2 \
            build s3://gm-code-bucket
